using ListaDeCompras.WebApplication.Compartilhado.Dominio;

namespace ListaDeCompras.WebApplication.ModuloListaDeCompras.Dominio;

public interface InterfaceRepositorioListasDeCompras : InterfaceRepositorio<ListasDeCompras>;