using ListaDeCompras.WebApplication.Compartilhado.Dominio;
using ListaDeCompras.WebApplication.ModuloItensDaLista.Dominio;

namespace ListaDeCompras.WebApplication.ModuloItensDaLista;

public interface InterfaceRepositorioItensDaLista : InterfaceRepositorio<ItensDaLista>;