using ListaDeCompras.WebApplication.Compartilhado.Dominio;

namespace ListaDeCompras.WebApplication.ModuloListasDeCompras.Dominio;

public interface InterfaceRepositorioListasDeCompras : InterfaceRepositorio<ListasDeCompras>;